### ISSUE TITLE
[BUG] RuntimeError: Unexpected model output: 26239

### ISSUE THREAD

**Issue by mali19064** [OpenBMB/BMInf#49]
**Describe the bug**

输入:
import bminf
cpm2 = bminf.models.CPM2()
result = cpm2.fill_blank("有一个服装品牌叫做<span>专门设计彩绘T恤", 
        top_p=0.5,
        top_n=5, 
        temperature=0.5,
        frequency_penalty=0,
        presence_penalty=0
        )

报错信息:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-7313124b5e28>", line 6, in <module>
    presence_penalty=0
  File "/usr/local/lib/python3.6/dist-packages/bminf/models/cpm2.py", line 252, in fill_blank
    raise RuntimeError("Unexpected model output: %d" % token)
RuntimeError: Unexpected model output: 26239

请帮忙看看是什么原因

**Environment:**
python3.6
torch1.8.1

**Comment by Arlenelalala** [comment]
我也遇到了这个问题，你解决了吗
